clonnedvideoapp/clonnedvideoapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from videos.views import signup, profile


urlpatterns = [
    path('admin/', admin.site.urls),
    path('videos/', include("videos.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/signup/", signup),
    path("accounts/profile/<int:user_id>/", profile, name="profile"),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

clonnedvideoapp/videos/urls.py
from unicodedata import name
from django.urls import path
from . import views


app_name = "videos"

urlpatterns = [
    path('', views.home, name="home" ),
    path('users/<int:pk>/', views.UserDetailView.as_view(), name="user_detail"),
    path('upload/', views.upload, name="video_upload"),
    path('watch/<int:video_id>/', views.watch, name="watch_video"),
]

clonnedvideoapp/recommendation_algorithm/models.py
from django.db import models

# Create your models here.

clonnedvideoapp/videos/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone


def get_current_date():
    return timezone.now()

class User(AbstractUser):
    is_private = models.BooleanField(default=False)


class Channel(models.Model):
    channel_name = models.CharField(max_length=50, unique=True)
    channel_creation_date = models.DateTimeField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.channel_name


class Video(models.Model):
    video_file = models.FileField(upload_to="videos")
    video_name = models.CharField(max_length=200)
    video_description = models.TextField()
    is_private = models.BooleanField(default=False, verbose_name="Is the video private?")
    post_date = models.DateTimeField(default=get_current_date)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.video_name

class Comment(models.Model):
    comment_text = models.TextField(max_length=1000)
    comment_post_date = models.DateTimeField(default=get_current_date)
    comment_is_edited = models.BooleanField(default=False)
    comment_likes = models.IntegerField(default=0)
    comment_dislikes = models.IntegerField(default=0)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    video = models.ForeignKey(Video, on_delete=models.CASCADE)
    reply = models.ForeignKey("self",on_delete=models.CASCADE, null=True, blank= True) 

    def __str__(self):
        return "This is a comment"

clonnedvideoapp/videos/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from .models import Video, Comment


class RegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)
    
    class Meta:
        model = get_user_model()
        fields = ["username", "password1", "password2", "email"]


class UploadVideoForm(forms.ModelForm):

    class Meta:
        model = Video
        fields = ["video_file", "video_name", "video_description","is_private"]
        exclude = ["author"]


class PostCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["comment_text"]

clonnedvideoapp/recommendation_algorithm/views.py
from django.shortcuts import render

# Create your views here.

clonnedvideoapp/videos/views.py
from http.client import HTTPResponse
from multiprocessing import context
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from .models import User, Channel, Video, Comment
from django.views import generic
from django.utils import timezone
from .forms import RegisterForm, UploadVideoForm, PostCommentForm
#from django.contrib.auth import views


def home(request):
    return render(request, "videos/home.html",{"message":"nothingimportant"})

def signup(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect("/accounts/login")
    else:
        form = RegisterForm()
    return render(request, "registration/signup.html",{"form": form}) 


@login_required
def profile(request, user_id):
    context = {
        "user": get_user_model().objects.get(pk = user_id),
        "videos": Video.objects.filter(author = user_id)
    }
    return render(request, "videos/profile.html", context)

@login_required
def upload(request):
    if request.method == "POST":
        form = UploadVideoForm(request.POST, request.FILES)
        if form.is_valid():
            video = form.save(commit=False)
            video.author = request.user
            video.save()
            return HttpResponseRedirect("/videos/")
    else:
        form = UploadVideoForm()
    return render(request, "videos/upload.html", {"form":form})


def watch(request, video_id):
    video = get_object_or_404(Video, pk = video_id)
    if request.method == "POST":
        form = PostCommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.video = video
            comment.save()
    else:
        form = PostCommentForm()
    
    context = {
        "video": video,
        "form": form,
    }
    return render(request, "videos/watch.html", context)

    



class IndexView(generic.ListView):
    pass



class UserDetailView(generic.DetailView):
    model = User
    template_name = "videos/user_detail.html"
    context_object_name = "user_detail"

clonnedvideoapp/videos/templates/videos/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="robots" content="index,follow">
    <meta name="description" content={% block head_description %}"Description"{% endblock head_description %}>
    <title>{% block title %}A title{% endblock title %}</title>
</head>
<body>
    {% block main_nav %}
        <nav>
            <a href="{% url 'videos:home' %}">Home</a>
            {% if user.id %}
                <a href="{% url 'profile' user.id %}">Profile</a>
            {% else %}
                <a href="{% url 'login' %}">Profile</a>
            {% endif %}
            <a href="">Navigation History</a>
            <a href="">About us</a>
            <a href="">Contact</a>
            <a href="{% url 'login' %}">Login</a>
            <a href="{% url 'videos:video_upload' %}">Upload</a>
        </nav>
    {% endblock main_nav %}
    
    {% block content %}
        <p>This is a sample text</p>
    {% endblock content %}

</body>
</html>

clonnedvideoapp/videos/templates/videos/home.html
{% extends 'videos/base.html' %}

{% block head_description %}
    "Home page"
{% endblock head_description %}

{% block title %}
    Home page
{% endblock title %}

{% block content %}
    This is the home page
{% endblock content %}

clonnedvideoapp/videos/templates/videos/index.html
<h1>
    No hay nada por el momento aqui
</h1>

clonnedvideoapp/videos/templates/videos/profile.html
{% extends 'videos/base.html' %}

{% block description %}User's profile page{% endblock description %}

{% block title %}{{user.username}}'s page{% endblock title %}

{% block content %}
    <h1>Username: {{user.username}}</h1>
    <ul>
        <li>
            First name: {% if user.first_name %} {{user.first_name}} {% else %}No provided {% endif %}
        </li>
        <li>
            Last name: {% if user.last_name %} {{user.last_name}} {% else %}No provided {% endif %}
        </li>
    </ul>
    
    <h2>
        Number of published videos: {{videos|length}}
        <ul>
            {% for video in videos %}
                <li>
                    <a href="{% url 'videos:watch_video' video.id %}">{{video.video_name}}</a>
                </li>
            {% endfor %}
        </ul>

    </h2>

{% endblock content %}

clonnedvideoapp/videos/templates/videos/upload.html
{% extends 'videos/base.html' %}

{% block description %}Upload a video{% endblock description %}

{% block title %}Upload Video{% endblock title %}

{% block content %}
    <form action="{% url 'videos:video_upload' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="Upload">
    </form>
{% endblock content %}

clonnedvideoapp/videos/templates/videos/user_detail.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="robots" content="index,follow">
        <meta name="description" content="User details">
        <title>User {{user_detail.username}} details</title>
        
    </head>
    <body>
        <h1>Username: {{user_detail.username}}</h1>
        <ul>
            <li>
                Email: {{user_detail.user_email}}
            </li>
            <li>
                Name: {{user_detail.user_name}}
            </li>
            <li>
                Last name: {{user_detail.user_last_name}}
            </li>
            <li>
                Register date (UTC): {{user_detail.user_register_date}}
            </li>
        </ul>
    </body>
</html>

clonnedvideoapp/videos/templates/videos/watch.html
{% extends 'videos/base.html' %}

{% block description %}Reproducing a video{% endblock description %}

{% block title %}{{video.video_name}}{% endblock title %}

{% block content %}
    <h1>{{video.video_name}}</h1><br>
    <video src="{{video.video_file.url}}" type="video/mp4" controls>
        This does not work
    </video><br>
    <div>
        <p>{{video.video_description}}</p>
    </div>
    <div>
        {{video.}}
    </div>
    <section>
        <h1>Comment section</h1>
        {% if video.comment_set.all %}
        <li>
            {% for comment in video.comment_set.all %}
                <ul>
                    {{comment.author}}:<br>
                    {{comment.comment_text}}
                </ul>
            {% endfor %}
        </li>
        {% else %}
        There are no comments in this video. Be the first in leave one!
        {% endif %}
        <form action="{% url 'videos:watch_video' video.id%}" method="post">
            {% csrf_token %}
            {{form}}
            <input type="submit" value="Post">
        </form>

    </section>

{% endblock content %}